[package]
name = "nbt"
version = "0.1.0"
edition.workspace = true

[dependencies]
slab.workspace = true
anyhow.workspace = true
byteorder.workspace = true
bytes.workspace = true
paste.workspace = true
num.workspace = true
cesu8.workspace = true
